# Generated by Django 5.2.6 on 2025-11-18 20:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialtoken',
            name='provider_user_id',
        ),
        migrations.AddField(
            model_name='socialtoken',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='socialtoken',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='socialtoken',
            name='provider',
            field=models.CharField(choices=[('linkedin', 'LinkedIn'), ('youtube', 'YouTube'), ('spotify', 'Spotify'), ('x', 'X')], max_length=20),
        ),
    ]
