# Generated by Django 5.2.6 on 2025-11-18 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0002_auto_20251118_2146'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialtoken',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
