# Generated by Django 5.2.8 on 2025-11-30 10:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0003_auto_20251118_2152'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='provider',
            field=models.CharField(choices=[('linkedin', 'LinkedIn'), ('youtube', 'YouTube'), ('spotify', 'Spotify'), ('x', 'X')], max_length=20),
        ),
        migrations.AlterField(
            model_name='socialtoken',
            name='access_token',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='socialtoken',
            name='refresh_token',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='socialtoken',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_tokens', to=settings.AUTH_USER_MODEL),
        ),
    ]
